const languages = [
  // Indo-European: Romance
  {
    code: "es",
    name: "Spanish",
    nativeName: "Español",
    phrase: "¿Quién más?",
    romanization: null,
    literalGloss: "Who more?",
    family: "Indo-European",
    branch: "Romance",
    speakers: 485000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Más' (more) carries the additive scalar meaning — functionally identical to English 'else'. Spanish uses the same interrogative-plus-additive structure found across all Romance languages.",
    audioLang: "es-ES",
    commonalityScore: 9,
    region: "europe-west",
    countries: ["es", "mx", "co", "ar", "pe", "cl", "ve", "ec", "cu", "us"],
    usagePerHour: 1.2,
    commonalityNote: "Highly social, group-oriented culture with compact 2-word phrase drives very frequent use in daily conversation.",
    universalPhraseTranslations: {
      "thank-you": "Gracias",
      "whats-your-name": "¿Cómo te llamas?",
      "how-much": "¿Cuánto?",
      "where-is": "¿Dónde está...?",
      "i-dont-know": "No sé",
      "lets-go": "¡Vámonos!",
    },
  },
  {
    code: "fr",
    name: "French",
    nativeName: "Français",
    phrase: "Qui d'autre ?",
    romanization: null,
    literalGloss: "Who of other?",
    family: "Indo-European",
    branch: "Romance",
    speakers: 310000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'D'autre' (of other) uses a partitive construction — literally 'who of the other ones?' — showing how French grammaticalizes the 'else' concept through a prepositional phrase.",
    audioLang: "fr-FR",
    commonalityScore: 6,
    region: "europe-west",
    countries: ["fr", "be", "ch", "ca", "sn", "ci", "cd", "cm", "mg"],
    usagePerHour: 0.5,
    commonalityNote: "The slightly longer partitive construction makes it marginally less spontaneous than the compact Spanish equivalent.",
    universalPhraseTranslations: {
      "thank-you": "Merci",
      "whats-your-name": "Comment tu t'appelles ?",
      "how-much": "Combien ?",
      "where-is": "Où est... ?",
      "i-dont-know": "Je ne sais pas",
      "lets-go": "Allons-y !",
    },
  },
  {
    code: "pt",
    name: "Portuguese",
    nativeName: "Português",
    phrase: "Quem mais?",
    romanization: null,
    literalGloss: "Who more?",
    family: "Indo-European",
    branch: "Romance",
    speakers: 260000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Mais' (more) mirrors Spanish 'más' — both descending from Latin 'magis'. The additive particle strategy is inherited directly from Vulgar Latin.",
    audioLang: "pt-BR",
    commonalityScore: 9,
    region: "south-america",
    countries: ["br", "pt", "ao", "mz"],
    usagePerHour: 1.2,
    commonalityNote: "Brazilian Portuguese culture is especially communal; compact phrase mirrors Spanish frequency patterns.",
    universalPhraseTranslations: {
      "thank-you": "Obrigado/a",
      "whats-your-name": "Como você se chama?",
      "how-much": "Quanto?",
      "where-is": "Onde fica...?",
      "i-dont-know": "Não sei",
      "lets-go": "Vamos!",
    },
  },
  {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
    phrase: "Chi altro?",
    romanization: null,
    literalGloss: "Who other?",
    family: "Indo-European",
    branch: "Romance",
    speakers: 85000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Altro' (other) derives from Latin 'alter'. Italian uniquely favors the 'other' strategy over the 'more' strategy used by Spanish and Portuguese.",
    audioLang: "it-IT",
    commonalityScore: 8,
    region: "europe-west",
    countries: ["it", "ch"],
    usagePerHour: 1.0,
    commonalityNote: "Animated conversational culture with frequent group discourse; compact phrase supports high usage.",
    universalPhraseTranslations: {
      "thank-you": "Grazie",
      "whats-your-name": "Come ti chiami?",
      "how-much": "Quanto?",
      "where-is": "Dov'è...?",
      "i-dont-know": "Non lo so",
      "lets-go": "Andiamo!",
    },
  },
  // Indo-European: Germanic
  {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
    phrase: "Wer noch?",
    romanization: null,
    literalGloss: "Who still/yet?",
    family: "Indo-European",
    branch: "Germanic",
    speakers: 135000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Noch' (still/yet) encodes temporal continuation — 'who is there still to add?' This temporal-additive strategy is distinctly Germanic and shared with Dutch.",
    audioLang: "de-DE",
    commonalityScore: 6,
    region: "europe-west",
    countries: ["de", "at", "ch"],
    usagePerHour: 0.5,
    commonalityNote: "More structured conversational norms reduce casual interrogative frequency compared to Romance languages.",
    universalPhraseTranslations: {
      "thank-you": "Danke",
      "whats-your-name": "Wie heißt du?",
      "how-much": "Wie viel?",
      "where-is": "Wo ist...?",
      "i-dont-know": "Ich weiß nicht",
      "lets-go": "Los geht's!",
    },
  },
  {
    code: "nl",
    name: "Dutch",
    nativeName: "Nederlands",
    phrase: "Wie nog?",
    romanization: null,
    literalGloss: "Who still?",
    family: "Indo-European",
    branch: "Germanic",
    speakers: 30000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Nog' (still) is cognate with German 'noch' — both from Proto-Germanic *nuka. Dutch preserves the same temporal-additive framing as its Germanic siblings.",
    audioLang: "nl-NL",
    commonalityScore: 6,
    region: "europe-west",
    countries: ["nl", "be", "sr"],
    usagePerHour: 0.5,
    commonalityNote: "Similar conversational profile to German; direct communication style with moderate interrogative frequency.",
    universalPhraseTranslations: {
      "thank-you": "Dank je",
      "whats-your-name": "Hoe heet je?",
      "how-much": "Hoeveel?",
      "where-is": "Waar is...?",
      "i-dont-know": "Ik weet het niet",
      "lets-go": "Laten we gaan!",
    },
  },
  {
    code: "sv",
    name: "Swedish",
    nativeName: "Svenska",
    phrase: "Vem annars?",
    romanization: null,
    literalGloss: "Who otherwise?",
    family: "Indo-European",
    branch: "Germanic",
    speakers: 13000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Annars' (otherwise/else) is a direct lexical equivalent of English 'else' — both from Proto-Germanic roots meaning 'other'. Swedish preserves this ancient cognate transparently.",
    audioLang: "sv-SE",
    commonalityScore: 5,
    region: "europe-west",
    countries: ["se", "fi"],
    usagePerHour: 0.3,
    commonalityNote: "Reserved Scandinavian communication style means less frequent casual interrogatives in group settings.",
    universalPhraseTranslations: {
      "thank-you": "Tack",
      "whats-your-name": "Vad heter du?",
      "how-much": "Hur mycket?",
      "where-is": "Var är...?",
      "i-dont-know": "Jag vet inte",
      "lets-go": "Nu kör vi!",
    },
  },
  // Indo-European: Slavic
  {
    code: "ru",
    name: "Russian",
    nativeName: "Русский",
    phrase: "Кто ещё?",
    romanization: "Kto yeshchyo?",
    literalGloss: "Who still/more?",
    family: "Indo-European",
    branch: "Slavic",
    speakers: 255000000,
    scriptDirection: "ltr",
    script: "Cyrillic",
    elseNote:
      "'Ещё' (yeshchyo) means 'still/yet/more' — it's a temporal-additive particle that asks 'who remains to be added?' This is the dominant strategy across all Slavic languages.",
    audioLang: "ru-RU",
    commonalityScore: 8,
    region: "europe-east",
    countries: ["ru", "by", "kz", "ua", "kg"],
    usagePerHour: 1.0,
    commonalityNote: "Direct, expressive conversational culture with frequent group enumeration in social contexts.",
    universalPhraseTranslations: {
      "thank-you": "Спасибо",
      "whats-your-name": "Как тебя зовут?",
      "how-much": "Сколько?",
      "where-is": "Где...?",
      "i-dont-know": "Я не знаю",
      "lets-go": "Пойдём!",
    },
  },
  {
    code: "pl",
    name: "Polish",
    nativeName: "Polski",
    phrase: "Kto jeszcze?",
    romanization: null,
    literalGloss: "Who still/yet?",
    family: "Indo-European",
    branch: "Slavic",
    speakers: 45000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Jeszcze' (yet/still) is cognate with Russian 'ещё' — both from Proto-Slavic *ešče. The temporal-additive pattern is strikingly uniform across the Slavic family.",
    audioLang: "pl-PL",
    commonalityScore: 7,
    region: "europe-east",
    countries: ["pl"],
    usagePerHour: 0.7,
    commonalityNote: "Warm social culture with communal gatherings; the phrase arises naturally in group planning contexts.",
    universalPhraseTranslations: {
      "thank-you": "Dziękuję",
      "whats-your-name": "Jak masz na imię?",
      "how-much": "Ile?",
      "where-is": "Gdzie jest...?",
      "i-dont-know": "Nie wiem",
      "lets-go": "Chodźmy!",
    },
  },
  // Indo-European: Indo-Aryan
  {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    phrase: "और कौन?",
    romanization: "Aur kaun?",
    literalGloss: "And who?",
    family: "Indo-European",
    branch: "Indo-Aryan",
    speakers: 600000000,
    scriptDirection: "ltr",
    script: "Devanagari",
    elseNote:
      "'और' (aur, meaning 'and') carries the additive function. Hindi places the additive particle before the interrogative — the reverse of English word order, but the semantic structure is identical.",
    audioLang: "hi-IN",
    commonalityScore: 10,
    region: "south-asia",
    countries: ["in", "np", "fj"],
    usagePerHour: 1.5,
    commonalityNote: "Extremely communal culture with large social groups; the compact 2-word phrase is ubiquitous in daily conversation.",
    universalPhraseTranslations: {
      "thank-you": "धन्यवाद",
      "whats-your-name": "आपका नाम क्या है?",
      "how-much": "कितना?",
      "where-is": "कहाँ है...?",
      "i-dont-know": "मुझे नहीं पता",
      "lets-go": "चलो!",
    },
  },
  {
    code: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
    phrase: "আর কে?",
    romanization: "Aar ke?",
    literalGloss: "And/more who?",
    family: "Indo-European",
    branch: "Indo-Aryan",
    speakers: 270000000,
    scriptDirection: "ltr",
    script: "Bengali",
    elseNote:
      "'আর' (aar) means 'and/more/else' — it's a single particle covering all additive meanings. Bengali mirrors Hindi's additive-first word order.",
    audioLang: "bn-IN",
    commonalityScore: 9,
    region: "south-asia",
    countries: ["bd", "in"],
    usagePerHour: 1.2,
    commonalityNote: "Dense social networks and communal culture in Bengal drive very high interrogative frequency.",
    universalPhraseTranslations: {
      "thank-you": "ধন্যবাদ",
      "whats-your-name": "তোমার নাম কী?",
      "how-much": "কত?",
      "where-is": "কোথায়...?",
      "i-dont-know": "আমি জানি না",
      "lets-go": "চলো!",
    },
  },
  // Indo-European: Iranian
  {
    code: "fa",
    name: "Farsi",
    nativeName: "فارسی",
    phrase: "کی دیگه؟",
    romanization: "Ki dige?",
    literalGloss: "Who other?",
    family: "Indo-European",
    branch: "Iranian",
    speakers: 110000000,
    scriptDirection: "rtl",
    script: "Arabic",
    elseNote:
      "'دیگه' (dige, colloquial form of 'digar') means 'other/another'. Farsi uses the 'other' strategy — the same root that gives us English 'else' via Proto-Indo-European *h₂élyos.",
    audioLang: "fa-IR",
    commonalityScore: 8,
    region: "middle-east",
    countries: ["ir", "af", "tj"],
    usagePerHour: 1.0,
    commonalityNote: "Iranian hospitality culture (taarof) creates frequent social enumeration contexts; colloquial form is very natural.",
    universalPhraseTranslations: {
      "thank-you": "ممنون",
      "whats-your-name": "اسمت چیه؟",
      "how-much": "چقدر؟",
      "where-is": "کجاست...؟",
      "i-dont-know": "نمی‌دونم",
      "lets-go": "!بریم",
    },
  },
  // Indo-European: Hellenic
  {
    code: "el",
    name: "Greek",
    nativeName: "Ελληνικά",
    phrase: "Ποιος άλλος;",
    romanization: "Poios allos?",
    literalGloss: "Who other?",
    family: "Indo-European",
    branch: "Hellenic",
    speakers: 13500000,
    scriptDirection: "ltr",
    script: "Greek",
    elseNote:
      "'Άλλος' (allos) means 'other' and is the direct ancestor of English 'else' through PIE *h₂élyos. Greek preserves one of the oldest attested forms of this universal concept.",
    audioLang: "el-GR",
    commonalityScore: 8,
    region: "europe-west",
    countries: ["gr", "cy"],
    usagePerHour: 1.0,
    commonalityNote: "Gregarious Mediterranean culture with lively group discourse; the phrase is a staple of social coordination.",
    universalPhraseTranslations: {
      "thank-you": "Ευχαριστώ",
      "whats-your-name": "Πώς σε λένε;",
      "how-much": "Πόσο;",
      "where-is": "Πού είναι...;",
      "i-dont-know": "Δεν ξέρω",
      "lets-go": "Πάμε!",
    },
  },
  // Semitic
  {
    code: "ar",
    name: "Arabic",
    nativeName: "العربية",
    phrase: "مَن أيضاً؟",
    romanization: "Man aydan?",
    literalGloss: "Who also?",
    family: "Afro-Asiatic",
    branch: "Semitic",
    speakers: 380000000,
    scriptDirection: "rtl",
    script: "Arabic",
    elseNote:
      "'أيضاً' (aydan) means 'also/too' — Arabic uses an additive particle strategy. The word derives from a root meaning 'to return', encoding the idea of 'who comes back/again in addition?'",
    audioLang: "ar-SA",
    commonalityScore: 9,
    region: "middle-east",
    countries: ["sa", "eg", "iq", "ma", "dz", "sd", "jo", "ae", "sy", "tn", "ly"],
    usagePerHour: 1.2,
    commonalityNote: "Deeply communal culture with strong traditions of group gathering (majlis); the phrase is essential in social coordination.",
    universalPhraseTranslations: {
      "thank-you": "شكراً",
      "whats-your-name": "ما اسمك؟",
      "how-much": "بكم؟",
      "where-is": "أين...؟",
      "i-dont-know": "لا أعرف",
      "lets-go": "!يلا",
    },
  },
  {
    code: "he",
    name: "Hebrew",
    nativeName: "עברית",
    phrase: "?מי עוד",
    romanization: "Mi od?",
    literalGloss: "Who still/more?",
    family: "Afro-Asiatic",
    branch: "Semitic",
    speakers: 9000000,
    scriptDirection: "rtl",
    script: "Hebrew",
    elseNote:
      "'עוד' (od) means 'still/more/again' — a temporal-additive particle. Despite Hebrew and Arabic being sister languages, they use different strategies: Hebrew favors 'still', Arabic favors 'also'.",
    audioLang: "he-IL",
    commonalityScore: 8,
    region: "middle-east",
    countries: ["il"],
    usagePerHour: 1.0,
    commonalityNote: "Israeli culture is famously direct and communal; the ultra-compact 'mi od?' is used constantly in group settings.",
    universalPhraseTranslations: {
      "thank-you": "תודה",
      "whats-your-name": "?מה שמך",
      "how-much": "?כמה",
      "where-is": "?...איפה",
      "i-dont-know": "אני לא יודע/ת",
      "lets-go": "!יאללה",
    },
  },
  {
    code: "am",
    name: "Amharic",
    nativeName: "አማርኛ",
    phrase: "ሌላ ማን?",
    romanization: "Lela man?",
    literalGloss: "Other who?",
    family: "Afro-Asiatic",
    branch: "Semitic",
    speakers: 57000000,
    scriptDirection: "ltr",
    script: "Ge'ez",
    elseNote:
      "'ሌላ' (lela) means 'other/another'. Amharic places the modifier before the interrogative and uses the 'other' strategy, making it typologically closer to Greek 'allos' than to its Semitic cousin Arabic.",
    audioLang: "am-ET",
    commonalityScore: 7,
    region: "east-africa",
    countries: ["et", "er"],
    usagePerHour: 0.7,
    commonalityNote: "Ethiopian communal dining (gursha) and social customs create natural contexts for group enumeration.",
    universalPhraseTranslations: {
      "thank-you": "አመሰግናለሁ",
      "whats-your-name": "ስምህ/ሽ ማን ነው?",
      "how-much": "ስንት?",
      "where-is": "የት ነው...?",
      "i-dont-know": "አላውቅም",
      "lets-go": "እንሂድ!",
    },
  },
  // Sino-Tibetan
  {
    code: "zh",
    name: "Mandarin Chinese",
    nativeName: "中文",
    phrase: "还有谁？",
    romanization: "Hái yǒu shéi?",
    literalGloss: "Still have who?",
    family: "Sino-Tibetan",
    branch: "Sinitic",
    speakers: 920000000,
    scriptDirection: "ltr",
    script: "Han (Simplified)",
    elseNote:
      "'还' (hái, still/also) + '有' (yǒu, have/exist) frames the question existentially: 'who still exists [to be counted]?' The verb 'have' makes the additive meaning explicit in a way unique to Chinese.",
    audioLang: "zh-CN",
    commonalityScore: 8,
    region: "east-asia",
    countries: ["cn", "tw", "sg", "my"],
    usagePerHour: 1.0,
    commonalityNote: "Group-oriented social dynamics and communal decision-making drive high frequency in everyday planning.",
    universalPhraseTranslations: {
      "thank-you": "谢谢",
      "whats-your-name": "你叫什么名字？",
      "how-much": "多少？",
      "where-is": "在哪里...？",
      "i-dont-know": "我不知道",
      "lets-go": "走吧！",
    },
  },
  {
    code: "yue",
    name: "Cantonese",
    nativeName: "廣東話",
    phrase: "仲有邊個？",
    romanization: "Zung6 jau5 bin1 go3?",
    literalGloss: "Still have which one?",
    family: "Sino-Tibetan",
    branch: "Sinitic",
    speakers: 85000000,
    scriptDirection: "ltr",
    script: "Han (Traditional)",
    elseNote:
      "'仲' (zung6, still) + '有' (jau5, have) parallels Mandarin, but Cantonese uses '邊個' (which one) instead of '誰' (who) — showing dialectal variation in the interrogative while preserving the additive frame.",
    audioLang: "zh-HK",
    commonalityScore: 8,
    region: "east-asia",
    countries: ["cn", "hk", "mo"],
    usagePerHour: 1.0,
    commonalityNote: "Cantonese culture is highly social with communal dining (yum cha); the phrase is a natural part of group coordination.",
    universalPhraseTranslations: {
      "thank-you": "多謝",
      "whats-your-name": "你叫咩名？",
      "how-much": "幾多？",
      "where-is": "喺邊度...？",
      "i-dont-know": "我唔知",
      "lets-go": "走啦！",
    },
  },
  {
    code: "bo",
    name: "Tibetan",
    nativeName: "བོད་སྐད",
    phrase: "གཞན་སུ་ཡོད?",
    romanization: "Zhän su yö?",
    literalGloss: "Other who exist?",
    family: "Sino-Tibetan",
    branch: "Tibetic",
    speakers: 6000000,
    scriptDirection: "ltr",
    script: "Tibetan",
    elseNote:
      "'གཞན' (zhän) means 'other' and 'ཡོད' (yö) is the existential verb 'to exist'. Tibetan combines the 'other' strategy with an existential framing, asking 'what other person exists?'",
    audioLang: "bo",
    commonalityScore: 4,
    region: "east-asia",
    countries: ["cn", "bt", "in"],
    usagePerHour: 0.2,
    commonalityNote: "Smaller speech community and more contemplative conversational norms mean less frequent casual interrogative use.",
    universalPhraseTranslations: {
      "thank-you": "ཐུགས་རྗེ་ཆེ",
      "whats-your-name": "ཁྱེད་རང་གི་མཚན་ལ་ག་རེ་ཟེར་གྱི་ཡོད?",
      "how-much": "གླ་ག་ཚོད?",
      "where-is": "ག་པར་ཡོད...?",
      "i-dont-know": "ང་མི་ཤེས",
      "lets-go": "འགྲོ!",
    },
  },
  // Japonic
  {
    code: "ja",
    name: "Japanese",
    nativeName: "日本語",
    phrase: "他に誰が？",
    romanization: "Hoka ni dare ga?",
    literalGloss: "Other-to who [subject]?",
    family: "Japonic",
    branch: "Japanese",
    speakers: 125000000,
    scriptDirection: "ltr",
    script: "Kanji + Hiragana",
    elseNote:
      "'他に' (hoka ni) means 'in addition to/other than' — Japanese uses a locative construction ('at the place of otherness') to encode 'else'. The particle 'に' marks the concept spatially.",
    audioLang: "ja-JP",
    commonalityScore: 5,
    region: "east-asia",
    countries: ["jp"],
    usagePerHour: 0.3,
    commonalityNote: "Indirect communication style (high-context culture) reduces overt interrogative frequency, though the concept is equally present.",
    universalPhraseTranslations: {
      "thank-you": "ありがとう",
      "whats-your-name": "お名前は？",
      "how-much": "いくら？",
      "where-is": "どこですか...？",
      "i-dont-know": "分かりません",
      "lets-go": "行こう！",
    },
  },
  // Koreanic
  {
    code: "ko",
    name: "Korean",
    nativeName: "한국어",
    phrase: "또 누구?",
    romanization: "Tto nugu?",
    literalGloss: "Again/also who?",
    family: "Koreanic",
    branch: "Korean",
    speakers: 82000000,
    scriptDirection: "ltr",
    script: "Hangul",
    elseNote:
      "'또' (tto) means 'again/also/too' — it's a repetitive-additive adverb. Korean frames 'else' as 'again', implying 'who comes up again in our enumeration?'",
    audioLang: "ko-KR",
    commonalityScore: 7,
    region: "east-asia",
    countries: ["kr", "kp"],
    usagePerHour: 0.7,
    commonalityNote: "Strong group culture (we-ness, 우리) with communal activities drives regular use in social coordination.",
    universalPhraseTranslations: {
      "thank-you": "감사합니다",
      "whats-your-name": "이름이 뭐예요?",
      "how-much": "얼마예요?",
      "where-is": "어디에...?",
      "i-dont-know": "몰라요",
      "lets-go": "가자!",
    },
  },
  // Dravidian
  {
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    phrase: "இன்னும் யார்?",
    romanization: "Innum yaar?",
    literalGloss: "Still/more who?",
    family: "Dravidian",
    branch: "South Dravidian",
    speakers: 78000000,
    scriptDirection: "ltr",
    script: "Tamil",
    elseNote:
      "'இன்னும்' (innum) means 'still/yet/more' — Tamil uses a temporal-additive strategy despite being completely unrelated to the Indo-European languages that use the same pattern. A powerful example of convergent evolution in grammar.",
    audioLang: "ta-IN",
    commonalityScore: 8,
    region: "south-asia",
    countries: ["in", "lk", "sg", "my"],
    usagePerHour: 1.0,
    commonalityNote: "Tamil culture is highly communal with extended family networks; group enumeration is a daily occurrence.",
    universalPhraseTranslations: {
      "thank-you": "நன்றி",
      "whats-your-name": "உங்கள் பெயர் என்ன?",
      "how-much": "எவ்வளவு?",
      "where-is": "எங்கே...?",
      "i-dont-know": "எனக்கு தெரியாது",
      "lets-go": "போகலாம்!",
    },
  },
  {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    phrase: "ఇంకా ఎవరు?",
    romanization: "Inkaa evaru?",
    literalGloss: "Still/more who?",
    family: "Dravidian",
    branch: "South-Central Dravidian",
    speakers: 83000000,
    scriptDirection: "ltr",
    script: "Telugu",
    elseNote:
      "'ఇంకా' (inkaa) means 'still/more/yet' — cognate with Tamil 'innum'. The Dravidian family independently developed the same temporal-additive strategy found in Germanic and Slavic languages.",
    audioLang: "te-IN",
    commonalityScore: 8,
    region: "south-asia",
    countries: ["in"],
    usagePerHour: 1.0,
    commonalityNote: "Similar communal dynamics to Tamil; joint family systems create constant contexts for group coordination.",
    universalPhraseTranslations: {
      "thank-you": "ధన్యవాదాలు",
      "whats-your-name": "మీ పేరు ఏమిటి?",
      "how-much": "ఎంత?",
      "where-is": "ఎక్కడ...?",
      "i-dont-know": "నాకు తెలియదు",
      "lets-go": "పదండి!",
    },
  },
  // Turkic
  {
    code: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
    phrase: "Başka kim?",
    romanization: null,
    literalGloss: "Other who?",
    family: "Turkic",
    branch: "Oghuz",
    speakers: 82000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Başka' means 'other/different' — from a root meaning 'head/chief', encoding otherness through the metaphor of 'a different head/person'. Turkish places the modifier before the interrogative.",
    audioLang: "tr-TR",
    commonalityScore: 8,
    region: "middle-east",
    countries: ["tr", "cy"],
    usagePerHour: 1.0,
    commonalityNote: "Turkish hospitality culture with frequent social gatherings (sohbet) makes this a natural and frequent phrase.",
    universalPhraseTranslations: {
      "thank-you": "Teşekkürler",
      "whats-your-name": "Adın ne?",
      "how-much": "Ne kadar?",
      "where-is": "Nerede...?",
      "i-dont-know": "Bilmiyorum",
      "lets-go": "Hadi gidelim!",
    },
  },
  {
    code: "uz",
    name: "Uzbek",
    nativeName: "Oʻzbekcha",
    phrase: "Yana kim?",
    romanization: null,
    literalGloss: "Again/more who?",
    family: "Turkic",
    branch: "Karluk",
    speakers: 35000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Yana' means 'again/more/also'. While Turkish uses 'other' (başka), Uzbek prefers the additive-repetitive strategy — showing divergence within the Turkic family itself.",
    audioLang: "uz",
    commonalityScore: 7,
    region: "central-asia",
    countries: ["uz", "kz"],
    usagePerHour: 0.7,
    commonalityNote: "Central Asian communal culture with strong traditions of collective hospitality (mehmon-navozlik).",
    universalPhraseTranslations: {
      "thank-you": "Rahmat",
      "whats-your-name": "Ismingiz nima?",
      "how-much": "Qancha?",
      "where-is": "Qayerda...?",
      "i-dont-know": "Bilmayman",
      "lets-go": "Ketdik!",
    },
  },
  // Niger-Congo
  {
    code: "sw",
    name: "Swahili",
    nativeName: "Kiswahili",
    phrase: "Nani mwingine?",
    romanization: null,
    literalGloss: "Who other?",
    family: "Niger-Congo",
    branch: "Bantu",
    speakers: 200000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Mwingine' means 'other/another' and belongs to noun class 1 (for people). Swahili's Bantu noun class system means the word for 'other' changes form depending on what you're asking about — 'mwingine' for people, 'kingine' for things.",
    audioLang: "sw",
    commonalityScore: 8,
    region: "east-africa",
    countries: ["ke", "tz", "ug", "cd", "rw"],
    usagePerHour: 1.0,
    commonalityNote: "East African communal culture (Ubuntu philosophy) with frequent group decision-making drives high usage.",
    universalPhraseTranslations: {
      "thank-you": "Asante",
      "whats-your-name": "Jina lako nani?",
      "how-much": "Bei gani?",
      "where-is": "Iko wapi...?",
      "i-dont-know": "Sijui",
      "lets-go": "Twende!",
    },
  },
  {
    code: "yo",
    name: "Yoruba",
    nativeName: "Yorùbá",
    phrase: "Tani mọ́?",
    romanization: null,
    literalGloss: "Who again/else?",
    family: "Niger-Congo",
    branch: "Volta-Niger",
    speakers: 50000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Mọ́' functions as an additive particle meaning 'again/else/more'. Yoruba is a tonal language, and the high tone on 'mọ́' distinguishes this additive meaning from other homophonous words.",
    audioLang: "yo",
    commonalityScore: 8,
    region: "west-africa",
    countries: ["ng", "bj", "tg"],
    usagePerHour: 1.0,
    commonalityNote: "Yoruba culture is famously communal with large extended family gatherings (idílé); the phrase is essential for social coordination.",
    universalPhraseTranslations: {
      "thank-you": "Ó ṣeun",
      "whats-your-name": "Kí ni orúkọ rẹ?",
      "how-much": "Èló ni?",
      "where-is": "Níbo ni...?",
      "i-dont-know": "Mi ò mọ̀",
      "lets-go": "Ẹ jẹ́ ká lọ!",
    },
  },
  {
    code: "zu",
    name: "Zulu",
    nativeName: "isiZulu",
    phrase: "Ubani omunye?",
    romanization: null,
    literalGloss: "Who other-one?",
    family: "Niger-Congo",
    branch: "Bantu",
    speakers: 28000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Omunye' means 'another one/other' and carries the class 1 prefix 'o-' for persons. Like Swahili, Zulu's noun class system morphologically encodes that we're asking about a person.",
    audioLang: "zu",
    commonalityScore: 8,
    region: "south-africa",
    countries: ["za"],
    usagePerHour: 1.0,
    commonalityNote: "Ubuntu ('I am because we are') philosophy means group inclusion is central; 'who else?' is a core social question.",
    universalPhraseTranslations: {
      "thank-you": "Ngiyabonga",
      "whats-your-name": "Ngubani igama lakho?",
      "how-much": "Malini?",
      "where-is": "Kuphi...?",
      "i-dont-know": "Angazi",
      "lets-go": "Masihambe!",
    },
  },
  // Austronesian
  {
    code: "id",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    phrase: "Siapa lagi?",
    romanization: null,
    literalGloss: "Who again/more?",
    family: "Austronesian",
    branch: "Malayo-Polynesian",
    speakers: 200000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Lagi' means 'again/more/still' — a versatile additive particle. Indonesian and Malay share this form, which also appears in informal contexts across Southeast Asian languages as a borrowing.",
    audioLang: "id-ID",
    commonalityScore: 8,
    region: "southeast-asia",
    countries: ["id", "my", "bn", "sg"],
    usagePerHour: 1.0,
    commonalityNote: "Indonesian communal culture (gotong royong — mutual cooperation) makes group coordination phrases very frequent.",
    universalPhraseTranslations: {
      "thank-you": "Terima kasih",
      "whats-your-name": "Siapa namamu?",
      "how-much": "Berapa?",
      "where-is": "Di mana...?",
      "i-dont-know": "Saya tidak tahu",
      "lets-go": "Ayo!",
    },
  },
  {
    code: "tl",
    name: "Tagalog",
    nativeName: "Tagalog",
    phrase: "Sino pa?",
    romanization: null,
    literalGloss: "Who still/else?",
    family: "Austronesian",
    branch: "Philippine",
    speakers: 82000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Pa' is a remarkably compact additive particle meaning 'still/else/more'. At just two letters, it's one of the shortest 'else' morphemes in any language — yet carries the full semantic weight.",
    audioLang: "fil-PH",
    commonalityScore: 10,
    region: "southeast-asia",
    countries: ["ph"],
    usagePerHour: 1.5,
    commonalityNote: "Filipino culture is extremely social (bayanihan spirit); the ultra-compact 2-syllable phrase makes it one of the most frequently used interrogatives.",
    universalPhraseTranslations: {
      "thank-you": "Salamat",
      "whats-your-name": "Anong pangalan mo?",
      "how-much": "Magkano?",
      "where-is": "Nasaan...?",
      "i-dont-know": "Hindi ko alam",
      "lets-go": "Tara!",
    },
  },
  {
    code: "haw",
    name: "Hawaiian",
    nativeName: "ʻŌlelo Hawaiʻi",
    phrase: "ʻO wai hou?",
    romanization: null,
    literalGloss: "Who new/again?",
    family: "Austronesian",
    branch: "Polynesian",
    speakers: 24000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Hou' means 'new/again' — Hawaiian frames 'else' through renewal, asking 'who is new [to this list]?' With only ~24,000 speakers, this endangered language still preserves this universal structure.",
    audioLang: "haw",
    commonalityScore: 3,
    region: "oceania",
    countries: ["us"],
    usagePerHour: 0.1,
    commonalityNote: "Critically endangered language with very small speaker community; conversational frequency is inherently limited by speaker population.",
    universalPhraseTranslations: {
      "thank-you": "Mahalo",
      "whats-your-name": "ʻO wai kou inoa?",
      "how-much": "ʻEhia?",
      "where-is": "Aia i hea...?",
      "i-dont-know": "ʻAʻole maopopo iaʻu",
      "lets-go": "E hele kākou!",
    },
  },
  // Austroasiatic
  {
    code: "vi",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    phrase: "Còn ai nữa?",
    romanization: null,
    literalGloss: "Remain who more?",
    family: "Austroasiatic",
    branch: "Vietic",
    speakers: 85000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Còn' (remain/still) + 'nữa' (more/again) double-marks the additive meaning, bracketing 'ai' (who). Vietnamese uses two particles where most languages use one — encoding both continuation and addition simultaneously.",
    audioLang: "vi-VN",
    commonalityScore: 8,
    region: "southeast-asia",
    countries: ["vn"],
    usagePerHour: 1.0,
    commonalityNote: "Vietnamese communal culture and group dining traditions create frequent natural contexts for this phrase.",
    universalPhraseTranslations: {
      "thank-you": "Cảm ơn",
      "whats-your-name": "Bạn tên gì?",
      "how-much": "Bao nhiêu?",
      "where-is": "Ở đâu...?",
      "i-dont-know": "Tôi không biết",
      "lets-go": "Đi thôi!",
    },
  },
  {
    code: "km",
    name: "Khmer",
    nativeName: "ភាសាខ្មែរ",
    phrase: "នរណាទៀត?",
    romanization: "Noronaa tiet?",
    literalGloss: "Who more/again?",
    family: "Austroasiatic",
    branch: "Khmeric",
    speakers: 18000000,
    scriptDirection: "ltr",
    script: "Khmer",
    elseNote:
      "'ទៀត' (tiet) means 'more/again/further'. Khmer uses the additive strategy, and like Vietnamese (its Austroasiatic relative), places the additive particle after the interrogative.",
    audioLang: "km",
    commonalityScore: 7,
    region: "southeast-asia",
    countries: ["kh"],
    usagePerHour: 0.7,
    commonalityNote: "Cambodian communal culture with family-centered social life supports regular interrogative use.",
    universalPhraseTranslations: {
      "thank-you": "អរគុណ",
      "whats-your-name": "អ្នកឈ្មោះអី?",
      "how-much": "ប៉ុន្មាន?",
      "where-is": "នៅឯណា...?",
      "i-dont-know": "ខ្ញុំមិនដឹង",
      "lets-go": "ទៅ!",
    },
  },
  // Uralic
  {
    code: "fi",
    name: "Finnish",
    nativeName: "Suomi",
    phrase: "Kuka muu?",
    romanization: null,
    literalGloss: "Who other?",
    family: "Uralic",
    branch: "Finnic",
    speakers: 5800000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Muu' means 'other/else'. Finnish, a non-Indo-European language surrounded by IE speakers, independently developed the same 'who + other' construction. The word 'muu' has no IE etymology — it's a Uralic original.",
    audioLang: "fi-FI",
    commonalityScore: 5,
    region: "europe-west",
    countries: ["fi"],
    usagePerHour: 0.3,
    commonalityNote: "Finnish communication style values silence and personal space; less frequent overt interrogation in group settings.",
    universalPhraseTranslations: {
      "thank-you": "Kiitos",
      "whats-your-name": "Mikä sinun nimesi on?",
      "how-much": "Paljonko?",
      "where-is": "Missä on...?",
      "i-dont-know": "En tiedä",
      "lets-go": "Mennään!",
    },
  },
  {
    code: "hu",
    name: "Hungarian",
    nativeName: "Magyar",
    phrase: "Ki más?",
    romanization: null,
    literalGloss: "Who other?",
    family: "Uralic",
    branch: "Ugric",
    speakers: 13000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Más' means 'other/different'. Despite being a Uralic language like Finnish, Hungarian uses a different root for 'other' — showing independent lexical choices within the same family while preserving the same syntactic strategy.",
    audioLang: "hu-HU",
    commonalityScore: 7,
    region: "europe-east",
    countries: ["hu"],
    usagePerHour: 0.7,
    commonalityNote: "Hungarian social culture is more expressive than Finnish; the compact two-word phrase is used frequently in casual settings.",
    universalPhraseTranslations: {
      "thank-you": "Köszönöm",
      "whats-your-name": "Mi a neved?",
      "how-much": "Mennyi?",
      "where-is": "Hol van...?",
      "i-dont-know": "Nem tudom",
      "lets-go": "Gyerünk!",
    },
  },
  // Kartvelian
  {
    code: "ka",
    name: "Georgian",
    nativeName: "ქართული",
    phrase: "კიდევ ვინ?",
    romanization: "Kidev vin?",
    literalGloss: "Still/more who?",
    family: "Kartvelian",
    branch: "Georgian",
    speakers: 3700000,
    scriptDirection: "ltr",
    script: "Georgian",
    elseNote:
      "'კიდევ' (kidev) means 'still/more/again'. Georgian — a language isolate family with no known relatives outside the Caucasus — uses the temporal-additive strategy independently. Its unique script (Mkhedruli) adds visual distinctiveness.",
    audioLang: "ka",
    commonalityScore: 7,
    region: "caucasus",
    countries: ["ge"],
    usagePerHour: 0.7,
    commonalityNote: "Georgian supra (feast) culture with elaborate toasting traditions creates frequent social enumeration contexts.",
    universalPhraseTranslations: {
      "thank-you": "მადლობა",
      "whats-your-name": "რა გქვია?",
      "how-much": "რამდენი?",
      "where-is": "სად არის...?",
      "i-dont-know": "არ ვიცი",
      "lets-go": "წავიდეთ!",
    },
  },
  // Language Isolate
  {
    code: "eu",
    name: "Basque",
    nativeName: "Euskara",
    phrase: "Beste nor?",
    romanization: null,
    literalGloss: "Other who?",
    family: "Language Isolate",
    branch: "Basque",
    speakers: 750000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Beste' means 'other/another'. Basque is Europe's only pre-Indo-European surviving language — its origins are unknown. Yet it constructs 'who else?' identically to its IE neighbors, suggesting this pattern may predate all known language families.",
    audioLang: "eu",
    commonalityScore: 6,
    region: "europe-west",
    countries: ["es", "fr"],
    usagePerHour: 0.5,
    commonalityNote: "Strong community identity (herri) with communal traditions, but smaller speaker population moderates frequency.",
    universalPhraseTranslations: {
      "thank-you": "Eskerrik asko",
      "whats-your-name": "Nola duzu izena?",
      "how-much": "Zenbat?",
      "where-is": "Non dago...?",
      "i-dont-know": "Ez dakit",
      "lets-go": "Goazen!",
    },
  },
  // Quechuan
  {
    code: "qu",
    name: "Quechua",
    nativeName: "Runasimi",
    phrase: "Pitaq?",
    romanization: null,
    literalGloss: "Who-else/and?",
    family: "Quechuan",
    branch: "Quechua",
    speakers: 10000000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'-taq' is an enclitic particle meaning 'and/else/also' — it attaches directly to 'pi' (who), creating a single fused word. Quechua encodes the additive meaning morphologically rather than as a separate word.",
    audioLang: "qu",
    commonalityScore: 7,
    region: "south-america",
    countries: ["pe", "bo", "ec"],
    usagePerHour: 0.7,
    commonalityNote: "Andean ayllu (community) system centers on collective labor; the morphologically compact form is efficient for group coordination.",
    universalPhraseTranslations: {
      "thank-you": "Sulpayki",
      "whats-your-name": "Iman sutiyki?",
      "how-much": "Hayk'a?",
      "where-is": "Maypin...?",
      "i-dont-know": "Mana yachanichu",
      "lets-go": "Hakuchik!",
    },
  },
  // Uto-Aztecan
  {
    code: "nah",
    name: "Nahuatl",
    nativeName: "Nāhuatl",
    phrase: "¿Aquin oc?",
    romanization: null,
    literalGloss: "Who still/yet?",
    family: "Uto-Aztecan",
    branch: "Aztecan",
    speakers: 1700000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Oc' means 'still/yet' — Nahuatl, the language of the Aztec Empire, uses a temporal particle just like Germanic and Slavic languages on the other side of the world. An extraordinary case of convergent grammatical evolution.",
    audioLang: "nah",
    commonalityScore: 5,
    region: "central-america",
    countries: ["mx"],
    usagePerHour: 0.3,
    commonalityNote: "Indigenous community settings with moderate speaker population; used regularly in communal contexts but less in urban daily life.",
    universalPhraseTranslations: {
      "thank-you": "Tlazohcamati",
      "whats-your-name": "¿Quen motoca?",
      "how-much": "¿Quezqui?",
      "where-is": "¿Canin...?",
      "i-dont-know": "Amo nicmati",
      "lets-go": "Ma tihuian!",
    },
  },
  // Polynesian
  {
    code: "mi",
    name: "Māori",
    nativeName: "Te Reo Māori",
    phrase: "Ko wai anō?",
    romanization: null,
    literalGloss: "Who again?",
    family: "Austronesian",
    branch: "Polynesian",
    speakers: 200000,
    scriptDirection: "ltr",
    script: "Latin",
    elseNote:
      "'Anō' means 'again/once more'. Māori frames 'else' through repetition — 'who again?' implies 'who is there when we go through the list once more?' Closely related to Hawaiian 'hou'.",
    audioLang: "mi",
    commonalityScore: 6,
    region: "oceania",
    countries: ["nz"],
    usagePerHour: 0.5,
    commonalityNote: "Māori culture is deeply communal (whānau, hapū, iwi); the phrase is important in hui (meetings) though the speaker population is small.",
    universalPhraseTranslations: {
      "thank-you": "Ngā mihi",
      "whats-your-name": "Ko wai tō ingoa?",
      "how-much": "E hia?",
      "where-is": "Kei hea...?",
      "i-dont-know": "Kāore au e mōhio",
      "lets-go": "Haere mai!",
    },
  },
  // Sign Language
  {
    code: "asl",
    name: "American Sign Language",
    nativeName: "ASL",
    phrase: "WHO ELSE? — Point outward with index finger while sweeping in an arc + open palm push forward",
    romanization: null,
    literalGloss: "WHO + ELSE (additive sweep gesture)",
    family: "Sign Language",
    branch: "French Sign family",
    speakers: 500000,
    scriptDirection: "ltr",
    script: "Visual-gestural",
    elseNote:
      "ASL expresses 'else' through a spatial sweep — the hand moves through physical space to indicate 'who among those others out there?' The spatial modality adds a dimension impossible in spoken language: the 'else' is literally pointing to the space where other people might be.",
    audioLang: null,
    commonalityScore: 8,
    region: "north-america",
    countries: ["us", "ca"],
    usagePerHour: 1.0,
    commonalityNote: "Deaf communities are tightly knit with frequent face-to-face interaction; the spatial expressiveness makes this a very natural and frequent sign.",
    universalPhraseTranslations: {
      "thank-you": "Flat hand from chin forward (THANK-YOU)",
      "whats-your-name": "Point + fingerspell NAME + palm-up question (YOUR NAME WHAT?)",
      "how-much": "Cupped hands bounce upward (HOW-MUCH?)",
      "where-is": "Wagging index finger + point (WHERE?)",
      "i-dont-know": "Open hand from forehead outward (DON'T-KNOW)",
      "lets-go": "Both hands sweep forward (LET'S-GO)",
    },
  },
];

// Language families for the family browser
const languageFamilies = [
  {
    name: "Indo-European",
    description: "The world's largest language family by speaker count",
    color: "#C9A84C",
  },
  {
    name: "Afro-Asiatic",
    description: "Ancient family spanning North Africa and the Middle East",
    color: "#E07A5F",
  },
  {
    name: "Sino-Tibetan",
    description:
      "Second-largest family, spanning East and Southeast Asia",
    color: "#81B29A",
  },
  {
    name: "Japonic",
    description: "Small family centered on the Japanese archipelago",
    color: "#F2CC8F",
  },
  {
    name: "Koreanic",
    description: "Small family centered on the Korean peninsula",
    color: "#E8A87C",
  },
  {
    name: "Dravidian",
    description: "Ancient family of South India, predating Indo-European arrival",
    color: "#D4A5A5",
  },
  {
    name: "Turkic",
    description: "Spanning Central Asia to Turkey",
    color: "#9CAFB7",
  },
  {
    name: "Niger-Congo",
    description: "Largest African family, including the vast Bantu branch",
    color: "#E6B89C",
  },
  {
    name: "Austronesian",
    description:
      "Spanning the Pacific and Indian Oceans — the most geographically spread family",
    color: "#9EC1CF",
  },
  {
    name: "Austroasiatic",
    description: "Ancient family of mainland Southeast Asia",
    color: "#A8D8B9",
  },
  {
    name: "Uralic",
    description:
      "Northern Eurasian family, including Finnish and Hungarian",
    color: "#B8B8D1",
  },
  {
    name: "Kartvelian",
    description: "Small family of the South Caucasus region",
    color: "#D4B483",
  },
  {
    name: "Language Isolate",
    description: "Languages with no known living relatives",
    color: "#C5C3C6",
  },
  {
    name: "Quechuan",
    description: "Major indigenous family of the Andes",
    color: "#DDBEA9",
  },
  {
    name: "Uto-Aztecan",
    description: "Major family of the Americas, from the US Southwest to Central America",
    color: "#CB997E",
  },
  {
    name: "Sign Language",
    description: "Visual-gestural languages with their own grammar and syntax",
    color: "#A5A58D",
  },
];

// Commonality score descriptors
const commonalityDescriptors = {
  10: { label: "Exceptionally High", estimate: "15+ uses/day", color: "#C9A84C" },
  9:  { label: "Very High", estimate: "12+ uses/day", color: "#C9A84C" },
  8:  { label: "High", estimate: "8–12 uses/day", color: "#E0C872" },
  7:  { label: "High", estimate: "6–8 uses/day", color: "#E0C872" },
  6:  { label: "Moderate", estimate: "~5 uses/day", color: "#D4CBBA" },
  5:  { label: "Moderate", estimate: "~3 uses/day", color: "#D4CBBA" },
  4:  { label: "Occasional", estimate: "~2 uses/day", color: "#9CAFB7" },
  3:  { label: "Occasional", estimate: "~1 use/day", color: "#9CAFB7" },
  2:  { label: "Rare", estimate: "<1 use/day", color: "#A08838" },
  1:  { label: "Very Rare", estimate: "infrequent", color: "#A08838" },
};

// Universal everyday phrases
const universalPhrases = [
  {
    id: "thank-you",
    english: "Thank you",
    universalityNote: "Present in all known languages. Often the first phrase learned by travelers.",
    structureMatch: "high",
  },
  {
    id: "whats-your-name",
    english: "What's your name?",
    universalityNote: "Universal interrogative. Structure varies — some languages use 'how are you called?' instead.",
    structureMatch: "medium",
  },
  {
    id: "how-much",
    english: "How much?",
    universalityNote: "Minimal interrogative found in every trade language. Structurally very consistent.",
    structureMatch: "high",
  },
  {
    id: "where-is",
    english: "Where is...?",
    universalityNote: "Spatial interrogative. All languages distinguish 'where' from 'what'.",
    structureMatch: "medium",
  },
  {
    id: "i-dont-know",
    english: "I don't know",
    universalityNote: "Epistemic negative — universally needed. Structure varies: some languages use a single word.",
    structureMatch: "low",
  },
  {
    id: "lets-go",
    english: "Let's go",
    universalityNote: "Hortative + motion verb. Remarkably consistent across families in both meaning and brevity.",
    structureMatch: "high",
  },
];

// Calculate total speakers
const totalSpeakers = languages.reduce((sum, lang) => sum + lang.speakers, 0);
const totalLanguages = languages.length;
